# Generated by Django 4.2.4 on 2023-10-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techelpAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
